version: '3.7'

services:
  web:
    build: .
    command: gunicorn python_webapp_django.wsgi:application --bind 0.0.0.0:8000 # python manage.py runserver 0.0.0.0:8000 #
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=morpheus
      - POSTGRES_PASSWORD=Morpheus@123
      - POSTGRES_DB=morpheus_db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 5080:80
      # - 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  # certs_volume:
  static_volume: